from enum import Enum


class Category(Enum):
    FOOD = 'FOOD'
    ENTERTAINMENT = 'ENTERTAINMENT'
    INVESTMENT = 'INVESTMENT'
    HOUSEHOLD = 'HOUSEHOLD'
    TRANSPORTATION = 'TRANSPORTATION'
    OTHER = 'OTHER'
