# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtChart import QChart, QChartView
from PyQt5.QtWidgets import QProgressBar

from view.item_view import TransactionDelegate


class Ui_MainView(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1034, 767)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 9, 1001, 721))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.generalButtonsLayout = QtWidgets.QHBoxLayout()
        self.generalButtonsLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.generalButtonsLayout.setContentsMargins(-1, -1, -1, 0)
        self.generalButtonsLayout.setSpacing(6)
        self.generalButtonsLayout.setObjectName("generalButtonsLayout")
        self.prevMonthButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.prevMonthButton.setObjectName("prevMonthButton")
        self.generalButtonsLayout.addWidget(self.prevMonthButton)
        self.nextMonthButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.nextMonthButton.setObjectName("nextMonthButton")
        self.generalButtonsLayout.addWidget(self.nextMonthButton)
        self.detailStatsButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.detailStatsButton.setObjectName("detailStatsButton")
        self.generalButtonsLayout.addWidget(self.detailStatsButton)
        self.mainLayout.addLayout(self.generalButtonsLayout)
        self.contentLayout = QtWidgets.QHBoxLayout()
        self.contentLayout.setSpacing(10)
        self.contentLayout.setObjectName("contentLayout")
        self.budgetLayout = QtWidgets.QVBoxLayout()
        self.budgetLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.budgetLayout.setContentsMargins(-1, -1, 0, -1)
        self.budgetLayout.setSpacing(10)
        self.budgetLayout.setObjectName("budgetLayout")
        self.budgetButtonsLayout = QtWidgets.QHBoxLayout()
        self.budgetButtonsLayout.setObjectName("budgetButtonsLayout")
        self.outcomesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.outcomesButton.setObjectName("outcomesButton")
        self.budgetButtonsLayout.addWidget(self.outcomesButton)
        self.incomesButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.incomesButton.setObjectName("incomesButton")
        self.budgetButtonsLayout.addWidget(self.incomesButton)
        self.budgetLayout.addLayout(self.budgetButtonsLayout)
        self.budgetList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        delegate = TransactionDelegate()
        self.budgetList.setItemDelegate(delegate)
        self.budgetList.setSpacing(10)
        self.budgetList.setObjectName("budgetList")
        self.budgetLayout.addWidget(self.budgetList)
        self.addTransactionButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.addTransactionButton.setObjectName("addTransactionButton")
        self.budgetLayout.addWidget(self.addTransactionButton)
        self.contentLayout.addLayout(self.budgetLayout)
        self.chartLayout = QtWidgets.QVBoxLayout()
        self.chartLayout.setObjectName("chartLayout")
        self.limitLayout = QtWidgets.QVBoxLayout()
        self.limitLayout.setObjectName("limitLayout")
        self.setLimitLayout = QtWidgets.QHBoxLayout()
        self.setLimitLayout.setObjectName("setLimitLayout")
        self.limitLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.limitLineEdit.setObjectName("lineEdit")
        self.limitLineEdit.setPlaceholderText("set limit of money you want to spend")
        self.setLimitLayout.addWidget(self.limitLineEdit)
        self.setLimitButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.setLimitButton.setObjectName("setLimitButton")
        self.setLimitLayout.addWidget(self.setLimitButton)
        self.limitLayout.addLayout(self.setLimitLayout)
        self.progress_bar = QProgressBar()
        self.limitLayout.addWidget(self.progress_bar)
        self.chartLayout.addLayout(self.limitLayout)
        self.chart = QChart()
        self.chart.setTitle('Wykres kolowy')
        self.chart_view = QChartView(self.chart)
        self.chartLayout.addWidget(self.chart_view)
        self.contentLayout.addLayout(self.chartLayout)
        self.mainLayout.addLayout(self.contentLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.prevMonthButton.setText(_translate("Form", "previous Month"))
        self.nextMonthButton.setText(_translate("Form", "next Month"))
        self.detailStatsButton.setText(_translate("Form", "detail statistics"))
        self.outcomesButton.setText(_translate("Form", "outcomes"))
        self.incomesButton.setText(_translate("Form", "incomes"))
        self.setLimitButton.setText(_translate("Form", "set limit"))
        self.addTransactionButton.setText(_translate("Form", "add transaction"))
